kind: pipeline
type: kubernetes
name: build-and-push

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: docker-build-and-push-to-harbor
    image: plugins/docker
    settings:
      # Thêm dòng này để chỉ định registry là Harbor
      registry: harbor.namth.online
      # Thay đổi repo để có định dạng của Harbor
      repo: harbor.namth.online/threads/threads-fe
      tags: 1.0.0-${DRONE_COMMIT_SHA:0:7}
      username:
        from_secret: harbor_username # Trỏ đến secret mới
      password:
        from_secret: harbor_password # Trỏ đến secret mới
      dockerfile: Dockerfile
      context: /drone/src
