kind: pipeline
type: kubernetes
name: build-and-push

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: dangnnam141002/threads-fe
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      context: /drone/src
