kind: pipeline
type: kubernetes
name: build-push-and-update-infra

trigger:
  branch:
    - main
  event:
    - push

steps:
  # === BƯỚC 1: BUILD VÀ PUSH IMAGE LÊN DOCKER HUB ===
  - name: build-and-push-to-dockerhub
    image: plugins/docker
    settings:
      repo: dangnam141002/threads-fe
      tags: 1.0.0-${DRONE_COMMIT_SHA:0:7}
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile
      context: /drone/src

  # === BƯỚC 2: CẬP NHẬT IMAGE TAG TRONG REPO INFRA ===
  - name: deploy
    image: line/kubectl-kustomize:1.31.0-5.7.1
    environment:
      REPO_URL:
        from_secret: repo_url
    commands:
      # 0. Cài thêm git vì image này không có sẵn
      - apk add --no-cache git

      # 1. Cấu hình thông tin người commit
      - git config --global user.name "namth1410"
      - git config --global user.email "tranhainam1410@gmail.com"

      # 2. Clone repo infra sử dụng token
      - git clone $REPO_URL

      # 3. Di chuyển vào đúng thư mục overlay cần cập nhật
      - cd threads-infra/manifests/overlays/dev/web

      # 4. Dùng kustomize để cập nhật image tag mới
      - |
        kustomize edit set image dangnam141002/threads-fe:latest=dangnam141002/threads-fe:1.0.0-${DRONE_COMMIT_SHA:0:7}

      # 5. Quay lại thư mục gốc của repo
      - cd ../../../../

      # 6. Add, commit và push thay đổi lên repo infra
      - git add .
      - 'git commit -m "ci: Update image for web to tag 1.0.0-${DRONE_COMMIT_SHA:0:7}"'

      - git remote set-url origin $REPO_URL
      - git push origin main
    depends_on:
      - build-and-push-to-dockerhub
