kind: pipeline
type: kubernetes
name: build-and-push

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --depth=1 https://github.com/namth1410/threads_fe.git .

  - name: docker-build
    image: plugins/docker
    settings:
      repo: dangnnam141002/threads-fe
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
